In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from random import randrange
from sklearn.metrics import confusion_matrix

# reading csv files
data =  pd.read_csv('D:/HomeWork/iris.data', sep=",",header = None)

for i in range(len(data)):
    if data.at[i , 4] == 'Iris-setosa':
        data.at[i ,4] = 0
    elif data.at[i , 4] == 'Iris-versicolor':
        data.at[i ,4] = 1
    elif data.at[i , 4] == 'Iris-virginica':
        data.at[i ,4] = 2

print(data)

       0    1    2    3  4
0    5.1  3.5  1.4  0.2  0
1    4.9  3.0  1.4  0.2  0
2    4.7  3.2  1.3  0.2  0
3    4.6  3.1  1.5  0.2  0
4    5.0  3.6  1.4  0.2  0
..   ...  ...  ...  ... ..
145  6.7  3.0  5.2  2.3  2
146  6.3  2.5  5.0  1.9  2
147  6.5  3.0  5.2  2.0  2
148  6.2  3.4  5.4  2.3  2
149  5.9  3.0  5.1  1.8  2

[150 rows x 5 columns]


In [2]:
class KNN:
    def __init__(self , X , Y , k):
        self.X_train = X
        self.Y_train = Y
        self.k = k
        
    def euclidean_distance(self , inst1 , inst2):
        distance = np.linalg.norm(inst1 - inst2)
        return distance
    
    
    def get_k_neighbors(self , inst1):
        distances=[]
        
        for inst2 in self.X_train:
            distances.append(self.euclidean_distance(inst1 , inst2))
            
        distances = np.asarray(distances)
        indices = np.argpartition(distances , self.k)
        k_self_indices = indices[:self.k]
        return k_self_indices
    
    
    def predict_class(self , inst1):
        
        knn_indices = self.get_k_neighbors(inst1)
        knn_labels= []
        
        for i in knn_indices:
            knn_labels.append(self.Y_train[i])
            
        occurrences = np.bincount(knn_labels)
        mode = np.argmax(occurrences)
        return mode
    
    def get_accuracy(self , Y_test , prediction):
        correct = Y_test == prediction
        acc = (np.sum(correct) / Y_test.shape[0])*100.0
        return acc

In [3]:
#insert data in arrays
y = data.iloc[:, 4].values
x = data.iloc[:, 0:4].values

In [22]:
#Cross Validation 10-Fold
k = [1 , 3 , 5 , 7 ,9 , 11 , 13 , 17 , 21 , 23 , 25 , 27 , 29 , 31 , 33 , 35 , 37 , 39 , 41 , 43 , 45 , 47 , 49 , 51]

for K in k :
    accuracy = []
    y_predicts = []
    for i in range(10):
        X = np.split(x, 10)
        Y = np.split(y, 10)
        
        X_Test = X[i]
        Y_Test = Y[i]
        
        X.pop(i)
        Y.pop(i)
        
        classifier = KNN(np.concatenate(X),np.concatenate(Y), K)
        preds = []
        for inst in X_Test :
            preds.append(classifier.predict_class(inst))
            y_predicts.append(classifier.predict_class(inst))
        accuracy.append(classifier.get_accuracy(Y_Test , preds))
    print('For K = ',K , 'Average of Validations ' , np.mean(accuracy))
    print('Confusion Matrix : \n' , confusion_matrix(y.tolist() , y_predicts))

For K =  1 Average of Validations  96.00000000000001
Confusion Matrix : 
 [[50  0  0]
 [ 0 47  3]
 [ 0  3 47]]
For K =  3 Average of Validations  94.66666666666666
Confusion Matrix : 
 [[50  0  0]
 [ 0 46  4]
 [ 0  4 46]]
For K =  5 Average of Validations  93.33333333333334
Confusion Matrix : 
 [[50  0  0]
 [ 0 45  5]
 [ 0  5 45]]
For K =  7 Average of Validations  93.33333333333334
Confusion Matrix : 
 [[50  0  0]
 [ 0 45  5]
 [ 0  5 45]]
For K =  9 Average of Validations  93.33333333333334
Confusion Matrix : 
 [[50  0  0]
 [ 0 46  4]
 [ 0  6 44]]
For K =  11 Average of Validations  93.33333333333334
Confusion Matrix : 
 [[50  0  0]
 [ 0 45  5]
 [ 0  5 45]]
For K =  13 Average of Validations  94.0
Confusion Matrix : 
 [[50  0  0]
 [ 0 45  5]
 [ 0  4 46]]
For K =  17 Average of Validations  92.66666666666667
Confusion Matrix : 
 [[50  0  0]
 [ 0 45  5]
 [ 0  6 44]]
For K =  21 Average of Validations  92.0
Confusion Matrix : 
 [[50  0  0]
 [ 0 45  5]
 [ 0  7 43]]
For K =  23 Average of 