In [1]:
import numpy as np
import pandas as pd
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from collections import Counter
import warnings
warnings.filterwarnings("ignore")

# reading csv files
data =  pd.read_csv(r'D:\HomeWork\Machine Learning\dataset\data_train.csv', sep=",",header = None)
test =  pd.read_csv(r'D:\HomeWork\Machine Learning\dataset\data_test.csv', sep=",",header = None)

goalTest = test.pop(16)
dfTest = test.copy()

goal = data.pop(16)
df = data.copy()

data.head()

0    1   2    3    4    5    6    7   8   9    10  11   12  13   14  15
0  47  100  27   81   57   37   26    0   0  23   56  53  100  90   40  98
1   0   89  27  100   42   75   29   45  15  15   37   0   69   2  100   6
2   0   57  31   68   72   90  100  100  76  75   50  51   28  25   16   0
3   0  100   7   92    5   68   19   45  86  34  100  45   74  23   67   0
4   0   67  49   83  100  100   81   80  60  60   40  40   33  20   47   0

In [2]:
def calculateAdaboost(X_train , y_train ,  estimators):
    adaboost = AdaBoostClassifier(n_estimators = estimators , learning_rate=1)
    adaboost.fit(X_train, y_train)
    return adaboost

In [3]:
# Function to calculate accuracy
def cal_accuracy(y_test, y_pred):
      
    print("Confusion Matrix: \n",
        confusion_matrix(y_test, y_pred))
      
    print ("\n Accuracy : \n",
    accuracy_score(y_test,y_pred)*100)
    
    print ("\n Precision : \n",
    precision_score(y_test,y_pred, average='macro')*100)

In [4]:
adaboost = calculateAdaboost(df , goal  , 10)
y_pred = adaboost.predict(dfTest)

cal_accuracy(goalTest,y_pred)

Confusion Matrix: 
 [[298   0   1   0   0   0  62   2   0   0]
 [  0 215 143   0   0   0   1   1   0   4]
 [  0   8 330   4   0   0  13   8   0   1]
 [  0   2 328   4   0   0   0   1   0   1]
 [  0   0   0   0 327   0  18   0   0  19]
 [  7   5  75  48   2   4  31 132   0  31]
 [  1   0   8   0   1   0 313  11   0   2]
 [  0  31  12   2   0   0   0 297   0  22]
 [ 59   0   1   0   0   1 104 150  21   0]
 [  0  13 186  12  12   0   2   1   0 110]]

 Accuracy : 
 54.859919954259574

 Precision : 
 63.656734702243035


In [5]:
c = calculateAdaboost(df , goal  , 5)
y_pred = c.predict(dfTest)

cal_accuracy(goalTest,y_pred)

Confusion Matrix: 
 [[328   0   1   1   1   0  25   0   7   0]
 [  0 135 216   3   9   0   1   0   0   0]
 [  0   0 338   5   0   0  13   8   0   0]
 [  0   2 329   4   0   0   0   0   0   1]
 [  0   5   0   3 336   0  18   0   0   2]
 [166   5  75  84   3   0   0   0   1   1]
 [  9   0   8   5   5   0 297  12   0   0]
 [  3  57  17   5  23   0   0 250   5   4]
 [165   0   2   0   1   0   1  63 104   0]
 [  0  33 188  41  34   0   0   0   1  39]]

 Accuracy : 
 52.34419668381932

 Precision : 
 54.86885187695163


In [6]:
c = calculateAdaboost(df , goal  , 20)
y_pred = c.predict(dfTest)

cal_accuracy(goalTest,y_pred)

Confusion Matrix: 
 [[323   0   1   0   1   0  26   0  12   0]
 [  0 207 138   5   0   0   2   0   0  12]
 [  0   8 334   1   0   0  13   8   0   0]
 [  0   2  60 245   0  19   9   0   0   1]
 [  1   9   3   0 324   0  19   0   0   8]
 [165  12   0 119   2  11  15   1   2   8]
 [  0   0   0   8   0   0 320   5   1   2]
 [  0  31  12   2   0   0   9 281   7  22]
 [184   0  11   0   0   0   6  32 103   0]
 [  0  16   9 168  12  30  20   0   1  80]]

 Accuracy : 
 63.693539165237276

 Precision : 
 63.87671039767271


In [7]:
c = calculateAdaboost(df , goal  , 50)
y_pred = c.predict(dfTest)

cal_accuracy(goalTest,y_pred)

Confusion Matrix: 
 [[336   0   1   0   0   0  23   0   3   0]
 [  0 212 138   5   4   0   2   0   0   3]
 [  0   8 334   1   0   0  13   8   0   0]
 [  0   2  60 245   0  19   9   0   0   1]
 [  1   9   3   0 325   0  19   0   0   7]
 [166  12   0 119   2  11  15   0   2   8]
 [  0   0   0   8   0   0 308   5  13   2]
 [  0  31  12   2   0   0   9 270  18  22]
 [264   0  10   0   0   0  12  28  22   0]
 [  1  24   9 168  12  30  20   0   0  72]]

 Accuracy : 
 61.03487707261293

 Precision : 
 59.05753716587541
